begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) values
 ('95000000-0000-4000-8000-000000000001','security-subject@example.invalid',now(),now(),now()),
 ('95000000-0000-4000-8000-000000000002','security-moderator@example.invalid',now(),now(),now()),
 ('95000000-0000-4000-8000-000000000003','security-founding@example.invalid',now(),now(),now());
insert into private.moderation_admins(user_id) values('95000000-0000-4000-8000-000000000002');
insert into private.founding_driver_admins(user_id) values('95000000-0000-4000-8000-000000000003');
insert into private.security_alert_recipients(user_id) values('95000000-0000-4000-8000-000000000002');
select ok(not has_table_privilege('authenticated','private.security_read_cases','select'),'case table is private');
select ok(not has_table_privilege('service_role','private.security_read_cases','select'),'service role has no direct case access');
select ok(not has_function_privilege('authenticated','private.read_freightiq_guarded_core(text,jsonb)','execute'),'library core has no client bypass');
select ok(not has_function_privilege('authenticated','private.read_operations_guarded_core(text,integer,jsonb)','execute'),'Operations core has no client bypass');
select ok(not has_function_privilege('authenticated','public.claim_security_alert_v1()','execute'),'clients cannot claim mail');
select ok(not has_function_privilege('anon','public.get_security_read_cases_v1(uuid,timestamptz,uuid)','execute'),'anonymous cannot inspect cases');
select ok(not has_function_privilege('authenticated','private.record_security_read(boolean,integer)','execute'),'clients cannot forge detection counters');
select ok(not (select detection_enabled or mail_enabled from private.security_response_config),'detection and mail default disabled');
update private.freightiq_read_guard_config set enabled=true,request_capacity=1,request_refill=0.001,
 metadata_capacity=10,metadata_refill=0.01,detail_capacity=10,detail_refill=0.01;
set local role authenticated;
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000001';
set local "request.method"='POST'; set local "request.headers"='{}';
select is(public.create_freightiq_stop_v1('security-fixture-stop','Security fixture',null,39,-108),'security-fixture-stop','fixture created with real API');
select throws_ok($$select public.get_security_read_cases_v1()$$,'42501','Moderator access required.','ordinary driver cannot review');
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000003';
select throws_ok($$select public.get_security_read_cases_v1()$$,'42501','Moderator access required.','Founding admin is not moderator');
reset role;
update private.security_response_config set detection_enabled=true,min_denied=2,min_disclosed=1,min_minutes=2;
insert into private.security_read_minutes(actor_key,minute,denied,disclosed)
values(private.security_actor('95000000-0000-4000-8000-000000000001'),date_trunc('minute',now())-interval '1 minute',0,1);
set local role authenticated;
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000001';
select ok(public.read_freightiq_guarded_v1('stop_detail','{"p_stop_id":"security-fixture-stop"}')->>'code' is null,'real guarded read returns content');
select is(public.read_freightiq_guarded_v1('stop_detail','{"p_stop_id":"security-fixture-stop"}')->>'code','FREIGHTIQ_READ_THROTTLED','real guard denial preserved');
reset role;
select is((select count(*) from private.security_read_cases),0::bigint,'one denial below synthetic threshold creates no case');
set local role authenticated;
select is(public.read_freightiq_guarded_v1('stop_detail','{"p_stop_id":"security-fixture-stop"}')->>'code','FREIGHTIQ_READ_THROTTLED','qualifying denial committed');
reset role;
select is((select count(*) from private.security_read_cases),1::bigint,'actual guard opens one case after sustained synthetic signal');
select is((select count(*) from private.security_alert_outbox),1::bigint,'case creates one approved-recipient delivery');
select set_config('test.case', (select id::text from private.security_read_cases),true);
select ok((select disclosed>=1 and denied>=2 and active_minutes=2 from private.security_read_cases),'case stores aggregate evidence');
set local role authenticated;
select public.read_freightiq_guarded_v1('stop_detail','{"p_stop_id":"security-fixture-stop"}');
reset role;
select is((select count(*) from private.security_alert_outbox),1::bigint,'repeated qualifying reads do not duplicate email');
set local role authenticated;
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000002';
select is(jsonb_array_length(public.get_security_read_cases_v1()->'cases'),1,'moderator sees case');
select ok(not ((public.get_security_read_cases_v1()->'cases'->0) ?| array['actor_key','subject_id','recipient']),'review reply excludes account key and recipient');
select throws_ok($$select public.act_security_read_case_v1(current_setting('test.case')::uuid,0,86401,'suspicious_collection')$$,'22023','Invalid action.','invalid duration rejected');
select lives_ok($$select public.act_security_read_case_v1(current_setting('test.case')::uuid,0,900,'suspicious_collection')$$,'moderator pause succeeds');
select throws_ok($$select public.act_security_read_case_v1(current_setting('test.case')::uuid,0,0,'mistake')$$,'PT409','Case changed. Reload before acting.','stale moderator action refused');
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000001';
select is(public.read_freightiq_guarded_v1('stop_detail','{"p_stop_id":"security-fixture-stop"}')->'data','null'::jsonb,'installed library interface withholds paused data');
select is(public.read_operations_guarded_v1()->>'code','OPERATIONS_READ_THROTTLED','installed Operations interface observes same pause');
select is(current_setting('response.status'),'429','pause emits refusal status');
select ok(public.save_freightiq_report_v1('security-fixture-stop') is not null,'real Intel saving remains available');
select ok(public.set_owned_freightiq_delivery_zone_v1('security-fixture-stop',39.01,-108.01),'real DZ saving remains available');
select is(public.get_owned_freightiq_stop_editor_v1('security-fixture-stop')->>'id','security-fixture-stop','own editor remains available');
select is(public.create_freightiq_stop_v1('security-second-stop','Still contributing',null,39,-108),'security-second-stop','real stop creation remains available');
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000002';
select lives_ok($$select public.act_security_read_case_v1(current_setting('test.case')::uuid,1,0,'review_complete')$$,'moderator restore succeeds');
reset role;
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000001';
select is(private.security_pause_seconds(),0,'restoration immediate');
select is((select count(*) from private.security_read_audit),2::bigint,'successful actions audited');
create function pg_temp.fail_security_audit() returns trigger language plpgsql as $$begin raise exception 'Synthetic audit failure'; end;$$;
create trigger test_security_audit_failure before insert on private.security_read_audit for each row execute function pg_temp.fail_security_audit();
set local role authenticated;
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000002';
select throws_ok($$select public.act_security_read_case_v1(current_setting('test.case')::uuid,2,900,'suspicious_collection')$$,'P0001','Synthetic audit failure','audit failure rejects moderator action');
reset role;
select is((select version from private.security_read_cases),2,'failed audit leaves version unchanged');
select ok((select paused_until is null from private.security_read_cases),'failed audit does not leave account paused');
drop trigger test_security_audit_failure on private.security_read_audit;
update private.security_read_cases set paused_until=clock_timestamp()-interval '1 second';
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000001';
select is(private.security_pause_seconds(),0,'expired pause ends without cleanup scheduler');
create function pg_temp.fail_security_record() returns trigger language plpgsql as $$begin raise exception 'Synthetic recording failure'; end;$$;
create trigger test_security_record_failure before insert on private.security_read_minutes for each row execute function pg_temp.fail_security_record();
set local role authenticated;
select is(public.read_freightiq_guarded_v1('stop_detail','{"p_stop_id":"security-fixture-stop"}')->>'code','FREIGHTIQ_READ_THROTTLED','recording failure does not disable rate enforcement');
reset role;
select ok((select last_record_failure_at is not null from private.security_response_config),'recording failure is visible to operator');
drop trigger test_security_record_failure on private.security_read_minutes;
set local role service_role;
select ok(public.claim_security_alert_v1() is null,'mail disabled blocks dispatch');
reset role;
update private.security_response_config set mail_enabled=true;
set local role service_role;
select set_config('test.claim',public.claim_security_alert_v1()::text,true);
select ok(current_setting('test.claim')::jsonb->>'leaseToken' is not null,'worker claim has lease');
select is(current_setting('test.claim')::jsonb->>'attempt','1','attempt persisted before send');
select ok(public.authorize_security_alert_v1((current_setting('test.claim')::jsonb->>'id')::uuid,(current_setting('test.claim')::jsonb->>'leaseToken')::uuid),'current approved recipient authorized immediately before sending');
reset role;
update auth.users set email='changed-security-moderator@example.invalid' where id='95000000-0000-4000-8000-000000000002';
set local role service_role;
select ok(not public.authorize_security_alert_v1((current_setting('test.claim')::jsonb->>'id')::uuid,(current_setting('test.claim')::jsonb->>'leaseToken')::uuid),'email change after claim prevents sending');
reset role;
update auth.users set email='security-moderator@example.invalid' where id='95000000-0000-4000-8000-000000000002';
update private.security_response_config set mail_enabled=false where singleton;
set local role service_role;
select ok(not public.authorize_security_alert_v1((current_setting('test.claim')::jsonb->>'id')::uuid,(current_setting('test.claim')::jsonb->>'leaseToken')::uuid),'mail disable after claim prevents sending');
reset role;
update private.security_response_config set mail_enabled=true where singleton;
set local role service_role;
select ok(public.claim_security_alert_v1() is null,'leased item cannot be claimed twice');
select ok(not public.complete_security_alert_v1((current_setting('test.claim')::jsonb->>'id')::uuid,gen_random_uuid(),'accepted',gen_random_uuid()),'stale lease cannot complete');
select ok(public.complete_security_alert_v1((current_setting('test.claim')::jsonb->>'id')::uuid,(current_setting('test.claim')::jsonb->>'leaseToken')::uuid,'retry'),'retry scheduled');
select ok(public.claim_security_alert_v1() is null,'backoff prevents immediate retry');
reset role;
update private.security_alert_outbox set next_attempt_at=now()-interval '1 second';
set local role service_role;
select set_config('test.claim2',public.claim_security_alert_v1()::text,true);
select is(current_setting('test.claim2')::jsonb->>'id',current_setting('test.claim')::jsonb->>'id','retry keeps stable delivery ID');
select is(current_setting('test.claim2')::jsonb->>'recipient',current_setting('test.claim')::jsonb->>'recipient','retry freezes recipient');
select is(current_setting('test.claim2')::jsonb->>'attempt','2','attempt increases');
reset role;
update private.security_alert_outbox set lease_until=now()-interval '1 second';
set local role service_role;
select ok(not public.authorize_security_alert_v1((current_setting('test.claim2')::jsonb->>'id')::uuid,(current_setting('test.claim2')::jsonb->>'leaseToken')::uuid),'expired lease cannot send');
select ok(not public.complete_security_alert_v1((current_setting('test.claim2')::jsonb->>'id')::uuid,(current_setting('test.claim2')::jsonb->>'leaseToken')::uuid,'accepted',gen_random_uuid()),'expired lease cannot complete');
reset role;
delete from private.moderation_admins where user_id='95000000-0000-4000-8000-000000000002';
set local role service_role;
select ok(public.claim_security_alert_v1() is null,'revoked moderator receives no new dispatch');
reset role;
select is((select state from private.security_alert_outbox),'cancelled','revoked recipient pending mail cancelled');
set local role authenticated;
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000002';
select throws_ok($$select public.get_security_read_cases_v1()$$,'42501','Moderator access required.','revocation prevents case access immediately');
reset role;
delete from auth.users where id='95000000-0000-4000-8000-000000000001';
select is((select count(*) from private.security_read_cases),0::bigint,'subject deletion removes keyed case');
select is((select count(*) from private.security_read_minutes),0::bigint,'subject deletion removes minute counters');
select is((select count(*) from private.security_read_audit),0::bigint,'subject deletion removes audit');
select is((select count(*) from private.security_alert_outbox),0::bigint,'subject deletion removes queued email');
insert into private.security_read_cases(actor_key,created_at,expires_at,denied,disclosed,active_minutes,paused_until)
values(private.security_actor('95000000-0000-4000-8000-000000000003'),now()-interval '31 days',now()-interval '1 day',1,1,2,now()+interval '1 hour');
set local "request.jwt.claim.sub"='95000000-0000-4000-8000-000000000003';
select is(private.security_pause_seconds(),0,'expired case cannot enforce a pause');
insert into private.security_read_minutes(actor_key,minute) values(private.security_actor('95000000-0000-4000-8000-000000000003'),now()-interval '111 minutes');
select private.purge_security_response();
select is((select count(*) from private.security_read_cases),0::bigint,'purge removes expired cases');
select is((select count(*) from private.security_read_minutes),0::bigint,'purge removes old minute accounting');
select * from finish();
rollback;
