begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,created_at,updated_at) values
 ('75000000-0000-4000-8000-000000000001','ops-guard@example.invalid',now(),now()),
 ('75000000-0000-4000-8000-000000000002','ops-guard-other@example.invalid',now(),now());
select ok(not has_function_privilege('anon','public.read_operations_guarded_v1(text,integer,jsonb)','execute'),'anonymous wrapper denied');
select ok(not has_function_privilege('service_role','public.read_operations_guarded_v1(text,integer,jsonb)','execute'),'service role has no extra grant');
select ok(not has_table_privilege('authenticated','private.operations_read_guard_config','select'),'configuration is private');
select ok(not has_table_privilege('authenticated','private.operations_read_guard_buckets','select'),'counters are private');
select ok(not (select prosecdef from pg_proc where oid='public.read_operations_guarded_v1(text,integer,jsonb)'::regprocedure),'public wrapper is invoker');
select ok((select prosecdef and proconfig @> array['search_path=""'] from pg_proc where oid='private.read_with_security_response(text,text,jsonb,text,integer,jsonb)'::regprocedure),'private implementation has fixed search path');
set local "request.jwt.claim.sub"='75000000-0000-4000-8000-000000000001';
set local "request.method"='POST';
set local "request.headers"='{}';
select is(public.read_operations_guarded_v1()->>'code','OPERATIONS_READ_NOT_CONFIGURED','disabled default discloses nothing');
select ok(public.read_operations_guarded_v1()->'data'='null'::jsonb,'unconfigured body has no condition data');
update private.operations_read_guard_config set enabled=true,request_capacity=2,request_refill=0.001,row_capacity=100,row_refill=0.03;
select ok(public.read_operations_guarded_v1(null,1,null)->'code'='null'::jsonb,'first request admitted');
select ok(public.read_operations_guarded_v1(null,1,null)->'code'='null'::jsonb,'second request admitted');
select is(public.read_operations_guarded_v1(null,1,null)->>'code','OPERATIONS_READ_THROTTLED','account request allowance exhausted');
select ok(public.read_operations_guarded_v1(null,1,null)->'data'='null'::jsonb,'refusal contains no data');
select is((select denied from private.operations_read_guard_buckets),2::bigint,'denial counters persist');
select is((select count(*) from private.freightiq_read_guard_buckets),0::bigint,'Operations does not spend stop-library allowance');
set local "request.jwt.claim.sub"='75000000-0000-4000-8000-000000000002';
select ok(public.read_operations_guarded_v1(null,1,null)->'code'='null'::jsonb,'second account allowance independent');
set local "request.method"='GET';
select throws_ok($$select public.read_operations_guarded_v1()$$,'PT405','POST required.','GET refused');
set local "request.method"='POST';
set local "request.headers"='{"prefer":"tx=rollback"}';
select is(public.read_operations_guarded_v1()->>'code','OPERATIONS_READ_INVALID','rollback preference refused');
set local "request.headers"='{}';
select is(public.read_operations_guarded_v1(null,101,null)->>'code','OPERATIONS_READ_INVALID','oversized page rejected');
update private.operations_read_guard_buckets set requests=2,remaining_rows=100;
select is(public.read_operations_guarded_v1('not-a-real-area',1,null)->>'code','OPERATIONS_READ_INVALID','invalid area returns safe error');
select is((select sum(failed) from private.operations_read_guard_buckets),1::numeric,'invalid inner request counted without data');
select is(public.read_operations_guarded_v1(null,1,jsonb_build_object('snapshot',repeat('0',64),'offset',0))->>'code','OPERATIONS_READ_INVALID','unsigned legacy cursor is rejected');
select is((select sum(failed) from private.operations_read_guard_buckets),2::numeric,'conflict counted, not delivered');
update private.operations_read_guard_buckets set requests=2,remaining_rows=0,updated_at=clock_timestamp();
select is(public.read_operations_guarded_v1('not-a-real-area',1,null)->>'code','OPERATIONS_READ_THROTTLED','exhausted row budget refuses before feed lookup');
select ok((public.read_operations_guarded_v1(null,1,null)->>'retry_after_seconds')::int>0,'refusal provides positive retry time');
delete from auth.users where id='75000000-0000-4000-8000-000000000002';
select is((select count(*) from private.operations_read_guard_buckets),1::bigint,'account deletion removes its counter');
select throws_ok($$select public.read_operations_guarded_v1()$$,'42501','Authentication required.','deleted account token cannot read');
update private.operations_read_guard_buckets set updated_at=clock_timestamp()-interval '61 minutes';
select private.purge_operations_read_guard();
select is((select count(*) from private.operations_read_guard_buckets),0::bigint,'idle counters expire');
select * from finish();
rollback;
